export const users = [
    {
        id:1,
        name:'Ayomide Aio',
        email:"Ayodasilva12@gmail.com",
        Followers:20,
        time:'5 mins ago',
        profileImage:"",
        postImage:"",
        desc:"Love for all , Hatred for none",
        likes:30,
        comments:'4 comments',
    },
    {
        id:2,
        name:'John Doe',
        email:"John@gmail.com",
        Followers:64,
        time:'51 mins ago',
        profileImage:"",
        postImage:"",
        desc:"love to my fams",
        likes:130,
        comments:'14 comments',
    },
    {
        id:3,
        name:'Greg Marllow',
        email:"greger@gmail.com",
        Followers:2,
        time:'2 mins ago',
        profileImage:"",
        postImage:"",
        desc:"I need me a boo",
        likes:40,
        comments:'14 comments',
    },
    {
        id:4,
        name:'Alex durden',
        email:"Alex12345@gmail.com",
        Followers:120,
        time:'50 mins ago',
        profileImage:"",
        postImage:"",
        desc:"Love from America",
        likes:3,
        comments:'4 comments',
    },
    {
        id:5,
        name:'Dora Hanks',
        email:"dorahanks09@gmail.com",
        Followers:202,
        time:'1 hrs ago',
        profileImage:"",
        postImage:"",
        desc:"Chillng with my people",
        likes:33,
        comments:'41 comments',
    }
]
   
    