import Head from 'next/head'

export default function Login() {
  return (
    <div className='bg-[#f8f2f2] h-screen w-screen pt-28 px-4'>
      <Head>
        <title>Facebook</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='  '>
        Hello Aio Users
      </div>
    </div>
  )
}
