import Head from 'next/head'
import Header from '../components/Header'
import Leftbar from '../components/Leftbar'
import Feed from '../components/Feed'
import Rightbar from '../components/Rightbar'

export default function Home() {
  return (
    <div className=''>
      <Head>
        <title>Facebook</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className=' '>
        <Header/>
        <div className=' flex p-2 '>
          <Leftbar className='' />
          <Feed/>
          <Rightbar/>
        </div>
      </div>
    </div>
  )
}
//h-screen w-screen p-2
