import Head from 'next/head'

export default function Login() {
  return (
    <div className='bg-[#f8f2f2] h-screen w-screen pt-28 px-4'>
      <Head>
        <title>Facebook</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='  '>
        <div className='flex flex-col items-center justify-center text-center space-y-10 md:flex-row md:space-x-4 '>
            <div className='md:text-left'>
                <p className='text-3xl font-bold text-blue-600'>AioSocial</p>
                <p>Connect with friends and the world around you on Aiosocial
                </p>
            </div>
            <div className='w-80 md:w-96 shadow-lg p-4 space-y-2 bg-white'>
                <input type="text" placeholder='Username' className='border text-sm border-slate-300 rounded-md p-2 outline-blue-300 w-full text-black '/>
                <input type="text" placeholder='Email' className='border text-sm border-slate-300 rounded-md p-2 outline-blue-300 w-full text-black '/>
                <input type="password" placeholder='Password...' className='border text-sm border-slate-300 rounded-md p-2 outline-blue-300 w-full text-black '/>
                <input type="password" placeholder='Retype Password...' className='border text-sm border-slate-300 rounded-md p-2 outline-blue-300 w-full text-black '/>
                <input type="submit" value='Log In'  className='border text-sm border-blue-500 rounded-md p-2 bg-blue-600 w-full text-white font-medium '/>
                <input type="button" value="Login ito account" className='border text-sm border-slate-300 rounded-md py-2 px-4  w-auto text-white bg-green-600'/>
            </div>
        </div>
      </div>
    </div>
  )
}
